services:
  db:
    image: postgres
    container_name: kino-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
  
  server:
    image: ghcr.io/teraa/kino:master
    container_name: kino-server
#    build:
#      context: .
#      dockerfile: Dockerfile
    depends_on:
      - "db"
    ports:
      - "5000:80"
    environment:
      - Db__ConnectionString=Host=db;Port=5432;Database=kino;Username=postgres;Password=example;Include Error Detail=true
      - ASPNETCORE_ENVIRONMENT=Development
      # - Serilog__WriteTo__Seq__Args__serverUrl=
      # - Serilog__WriteTo__Seq__Args__apiKey=
